language: scala
scala:
- 2.11.6
script: sbt clean test
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - peter.rigole@atomicbits.io
after_success:
- '[[ $TRAVIS_BRANCH == "develop" ]] && { sbt publish; };'

env:
  global:
  - secure: gfeKN+bGlG6LkD1yBxdY37D+12elwoBjVov1n4Slyp1L4OTWz+c9XG6kbqh9H/kiipbniFN1w/+O0cMlczKp9UzBchSHeq2U88IWDPCWFMysAIZVIahllfVj68om16wZU2SQLiM0SV91Qlzu7isvAn8kvY/Btu6Xm3qZNmxj9TWgVKdURXyf6U/boEl43WYk5RzdmaPoUCMn14cil0fuBkzwlqYuh7Ipq7EeDVskdcA7gJDfkC1c6VZW6L4DVqofFn1qE1PgyEfi1UV8qMyx6maMRhb8JzQoWWkOT141+GoV/iUnZ3wtrjWGno76u9teS2MPxPtUOE6yb7hut3nHg72oPyXmiSborflQn8/YRuj3setcJpByvnSAcWAB2HVQnLzbXX99DKFUDEtNI1go1JiPfut/p4lj9KUe7MMR3Z8LyvyY0DGw5C9wnNjL1PMW7zBX81f1qhbsEtujmvYcBvz2AoMuL02+f3TTXpulJK92Cqjt2d7v5kQI09Dtzz1ceNvUhNPR/LloFjF3KOZNMEtntbM79khEDtHk9nm1BZAfyAkIqhcH+SrEvz4PzW8yD4pf1HhLb6q4TSipSWPBHILhRclwmyHwJJofd10UIhLUv9yinq0WeDdbvzXx2+nmBWHucV+EugGO0oi/ddwsMeTaaP/U7vAdHN9n9GgoDzE=
  - secure: e0JYLXPinY6XtKt+EXwMoNjGL0JIkkMmDUABCiErMt6/vhT1c0lfMhNypo3vp4dp2hHvTRB5gjVuwcE/SqJi5BljqegjVd3oeRY3+H8HH7d0ymMSuWc2FTsqS7MgkARRx2tBKFXJOZVSNs9wqMwYYIQXhZml5brSNU8iwjsW2yzt8pJ1wejaiZjvPtXaWzZjMIyrg9EYZSKWhT7XqAercNMZHsGN+rNhLKPC7r8QgSnzxmyqrVEmNeCqKRIANt1GiNP2bdoUYIMBKUnYRlxVCOm4MVqRteI6Pvr+ITTt4Gjsk2X/AoVr0R17WMtjhCmNlNGHMrUz/DN3/Mh5HzEfRnlq5sFqkbI+oAzITiJYqPYZK442D3STCzg2MNB7gu08lq1aliQY2BjKM2EAp6be+2Gxw49rDJFOknGnT4irqzFbVxap7EbGHDzWt1T3WpB3Sm36cHuVtwPwpRzpr92ORXze3HUSzx5h5M/c7bDFahsgxXxH7JXMr3KvMkPCFMSa3VtmZGyz+N7W6vfn9WPVR96jacpVdETDMvmok6iqt9KPblYvEonDbQ9tas6H4ghiV+0UwP6HmzMhcoRz0zcdlSdLos4ueXejqJjbwLiQE59231FY2pHg2mf3dY+P5llg1O9x52zv22ZYPmwF2cmMpDNAM2KsNQ3mAqdHCUOeydY=
